# Running on Ubuntu 18.04 (aws/codebuild/standard:4.0)
# https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile
version: 0.2

phases:
  pre_build:
    commands:
      - echo "No pre build commands"
  build:
    commands:
      - eval $BUILD_COMMAND
  post_build:
    commands:
      - aws s3 sync --delete $BUILD_OUTPUT_DIR s3://$AWS_S3_WEBSITE_BUCKET
      - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
